### ISSUE TITLE
Facebook default image

### ISSUE THREAD

**Issue by valencik** [SMUhackaweek/SMU-Hack-A-Week#23]
Can we do some investigating to find out by what criteria Facebook selects an image from a website to use in linked posts?
Currently facebook posts linking to the hackaweek page grab the Frontier logo, can we do somethign to influence this?
Ideally Facebook should use the top SMU hackaweek banner.

**Comment by kashifkai28** [comment]
The reason why we don't see hackaweek banner is: firstly, facebook uses banner images that are atleast 200 * 200 pixels, ours is 1015 × 150. Secondly, we havent told facebook (precisely in our code) use this banner image whenever this link is shared.

<meta property="og:image" content="YOURIMAGEURLGOESHERE.JPG">
This would let facebook know that whenever this website link is shared, use the above image url always.

To add more swag ...
<meta property="og:description" content="Hack-A-Week description">
We can actually control what text should be displayed in our shared Link. 

Checkout this facebook online debugger - https://developers.facebook.com/tools/debug/og/object/

Enter the website url and enjoy the magic :)

**Comment by kashifkai28** [comment]
Sorry for the delay. I wasted 2 hours debugging the wrong URL link. 

Is this ok? 
![screen shot 2015-04-26 at 11 32 14 pm](https://cloud.githubusercontent.com/assets/6319553/7340842/b20e460a-ec6c-11e4-978d-265a2ff6cee1.png)

**Comment by valencik** [comment]
That's fine for now.
If the actual image's background is that poor quality though we'll have to come up with something else.
Perhaps a new image from the source background.
But this works for now, update the PR and I will merge. Thanks!

**Comment by kashifkai28** [comment]
Yes the background got blurred while I was trying make a square image. 
Should I close the issues again in my commit?
